name: ovip2
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0

cupertino_icons: ^1.0.2
linked_scroll_controller: ^0.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.ovip2
    iosBundleIdentifier: com.example.ovip2
